### ISSUE TITLE
How to plot 3d OCTA volume?

### ISSUE THREAD

**Issue by roshideen** [chaosallen/IPN_tensorflow#2]
Hi,
Can you suggest (or share code if possible) how to plot 3d volume of OCTA image from b-scan oct and octa images?

**Comment by chaosallen** [comment]
Many 3D visualization software can achieve it, such as Mimics,Amira,&nbsp;plug-in of ImageJ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaosallen/IPN_tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 上午7:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaosallen/IPN_tensorflow] How to plot 3d OCTA volume? (#2)





 
Hi,
 Can you suggest (or share code if possible) how to plot 3d volume of OCTA image from b-scan oct and octa images?

**Comment by roshideen** [comment]
Thank you very much
